name: improc_env
channels:
  - conda-forge
dependencies:
  - python=3.7
  - numpy
  - matplotlib
  - scikit-image
  - pandas
  - ipyvolume
  - pip
  - voila
  - itkwidgets
  - pip:
    - trackpy
    - tensorflow
    - keras
    - tqdm